name: Docs deployment

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.20.3
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm run docs:build
    - run: cd docs/.vitepress/dist
    - run: git init
    - run: git config user.name "${GITHUB_ACTOR}"
    - run: git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
    - run: git add -A
    - run: git commit -m 'deploy'
    - run: git push -f https://jinjiang:${{secrets.ACCESS_TOKEN}}@github.com/Jinjiang/zhlint.git master:gh-pages
    - run: cd -
